### ISSUE TITLE
Documentation manquante

### ISSUE THREAD

**Issue by kilbith** [ElementW/Diggler#2]
Salut, pourrais-tu donner quelques indications pour compiler Diggler stp ? (librairies nécessaires, options cmake, etc.).

**Comment by ElementW** [comment]
Cf le [README.md](https://github.com/gravgun/Diggler/blob/91ede2629a3929e660aa9b75e5691efbba955e5e/README.md) que je viens juste d'ajouter. C'est qu'une ébauche mais normalement ça devrait suffire. Après, un coup de `cmake` et `make`.

**Comment by kilbith** [comment]
OK merci. Par contre je n'arrive toujours pas à construire mon cmake :

```
[jp@r2d2 Diggler]$ cmake .
CMake Error at CMakeLists.txt:12 (string):
  string sub-command FIND requires 3 or 4 parameters.


CMake Error at CMakeLists.txt:14 (if):
  if given arguments:

    "EQUAL" "0"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/jp/Diggler/CMakeFiles/CMakeOutput.log".
```

**Comment by ElementW** [comment]
eb7864a662b93fb45ff5326a788eff372cba0f9e J'ai jamais croisé le problème avant, je compile toujours les projets CMake dans un sous-dossier "build". Fixé.

**Comment by kilbith** [comment]
C'est bon, merci.
