### ISSUE TITLE
"Could not connect to server"

### ISSUE THREAD

**Issue by kilbith** [ElementW/Diggler#3]
En lançant Diggler, je reste bloqué à cette étape : 

![capture d ecran de 2016-01-30 13-21-37](https://cloud.githubusercontent.com/assets/7883281/12695622/9817e698-c754-11e5-9b0f-6f38cebfd3c7.png)

Je suis censé faire quoi ?

**Comment by ElementW** [comment]
C'est pas encore documenté non plus mais il faut que tu lances un serveur en local avec `./diggler -s`, puis que tu lances le jeu. Dans un futur proche je ferais un menu qui permettra de lancer un serveur en local (solo).

**Comment by farfadet46** [comment]
tu peut nous filer-compiler l’exécutable Windows ?

**Comment by ElementW** [comment]
@farfadet46 Non car je n'ai pas de quoi cross-compiler (c'est un enfer à gérer), ni n'ai Windows (ni n'aie l'envie de m'en servir étant donné ce qui se passe en ce moment avec), ni n'ai fait en sorte que le jeu compile dessus (même si il devrait sans soucis), désolé. Tu peux ouvrir une nouvelle issue à ce propos tu veux.

**Comment by ObaniGemini** [comment]
I think this issue can be closed ?
