### ISSUE TITLE
Frustum culling défaillant

### ISSUE THREAD

**Issue by kilbith** [ElementW/Diggler#4]
Visiblement y'a un problème avec le frustum culling, les faces supposées visibles ne sont pas rendues : 

![capture d ecran de 2016-01-30 14-34-15](https://cloud.githubusercontent.com/assets/7883281/12696010/ade230a0-c75e-11e5-828f-5a692016198e.png)

**Comment by ElementW** [comment]
:O Tout est encore cassé! Il y a pas si longtemps tout fonctionnait très bien. Je regarde.

**Comment by ElementW** [comment]
e1b8b5baa878a5fe3d173317d807e7482d13ee93 J'avais changé mon vrai modulo `rmod` vers `std::remainder` sans vérifier que ça marchait.
