### ISSUE TITLE
The mouse movment is incontrolable

### ISSUE THREAD

**Issue by farfadet46** [ElementW/Diggler#5]
https://up1.ca/#HeJqIPPBnZSdz9_nByOtQA

**Comment by ObaniGemini** [comment]
Do you mean that you can't contol the mouse ?
Could you describe the problem a bit more ? (OS, desktop environemment, how did it occur,... )

**Comment by ElementW** [comment]
Can't fix, not my bug. GLFW fails to lock pointer under XWayland (and so does every single toolkit out there) since Wayland doesn't yet properly implement pointer locking.

You may try to use a self-compiled version of GLFW3 with the `-DGLFW_USE_WAYLAND=ON` option, though.
