### ISSUE TITLE
CMake trivial error

### ISSUE THREAD

**Issue by ObaniGemini** [ElementW/Diggler#8]
When generating makefile with cmake, this happens.

CMake Error at CMakeLists.txt:155 (add_executable):
  Cannot find source file:

    /home/me/Desktop/Diggler/src/GLFWHandler.cpp

This is because of last GLFW related commits, I guess you could just get rid of `GLFWHandler.cpp` in src/CMakeLists.txt`

**Comment by ElementW** [comment]
334540ca987c01809058a79526848084ecd0c9a4
